[API_KEYS]
OPENAI_API_KEY = "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"
PINECONE_API_KEY = "pcsk_m74DA_EoW1zexNTdNSVetA3abdZTgf8su66GumFShesKigC49TLeiHqxwtM6bAyDAWjfQ"